#!/bin/bash -e

# Vercel's NPM is too old T.T
rm -f package-lock.json

npm i
mkdir public
mv *.html ui-* ci node_modules public/

# Build in `wa/` if available
if [ -e wa ]; then ( cd wa; npm run vercel-build ); fi

# Export `ext/` if available
if [ -e ext ]; then mv ext public/ ; fi

# Export `fun/` if available
if [ -e fun ]; then mv fun public/ ; fi
