#!/bin/bash -e

# Vercel's NPM is too old T.T
rm -f package-lock.json
rm -rf public  # need to clean up older build?

npm i
mkdir public
mv *.html frontend ci node_modules public/

# Build in `wa/` if available
if [ -e wa ]; then ( cd wa; npm run vercel-build ); fi

# Export `examples/` if available
if [ -e examples ]; then mv examples public/ ; fi

# Export `ext/` if available
if [ -e ext ]; then mv ext public/ ; fi

# Export `fun/` if available
if [ -e fun ]; then mv fun public/ ; fi
