#!/bin/bash -e

# Vercel's NPM is too old T.T
rm -f package-lock.json

npm i

# Vercel does not like (some) symlinks :/
varnishLinks() {
    for fn in * ; do
        tgt=$(readlink $fn || true)
        if [ x"$tgt" != x ] ; then
            echo "$fn --> $tgt"
            rm $fn
            cp -R $tgt ./$fn
        fi
    done
}

( cd node_modules/wacoq-bin/bin && varnishLinks )

mkdir ../public/wa
mv *.html ui-* ci node_modules ../public/wa
